services:
  app:
    image: tournament-app:latest
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    networks:
      app-network:
        ipv4_address: 10.0.1.10 # why do we need to specify the ip address? -
      db-network:
        ipv4_address: 10.0.2.10 # dbye network ile bağlamadağım için baya hata yaşadım .d 
    profiles:
      - default
      - test
    volumes:
    - ./report.xml:/app/report.xml

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      db-network:
        ipv4_address: 10.0.2.11
    profiles:
      - default
      - test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "6379:6379"
    networks:
      db-network:
        ipv4_address: 10.0.2.12
    profiles:
      - default
      - test

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
  db-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24